# Generated by Django 5.2.13 on 2026-06-23 22:38

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dobavljac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=200)),
                ('oib', models.CharField(blank=True, max_length=11)),
                ('kontakt_osoba', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefon', models.CharField(blank=True, max_length=20)),
                ('adresa', models.TextField(blank=True)),
                ('aktivan', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Dobavljač',
                'verbose_name_plural': 'Dobavljači',
                'ordering': ['naziv'],
            },
        ),
        migrations.CreateModel(
            name='EvidencijaRada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mjesec', models.PositiveSmallIntegerField()),
                ('godina', models.PositiveIntegerField()),
                ('ostvareni_sati', models.DecimalField(decimal_places=2, max_digits=5)),
                ('napomena', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Evidencija rada',
                'verbose_name_plural': 'Evidencije rada',
                'ordering': ['-godina', '-mjesec'],
            },
        ),
        migrations.CreateModel(
            name='JedinicaMjere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'Jedinica mjere',
                'verbose_name_plural': 'Jedinice mjere',
                'ordering': ['naziv'],
            },
        ),
        migrations.CreateModel(
            name='Pozicija',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Pozicija',
                'verbose_name_plural': 'Pozicije',
                'ordering': ['naziv'],
            },
        ),
        migrations.CreateModel(
            name='Korisnik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Korisnik',
                'verbose_name_plural': 'Korisnici',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='BonusOdbitak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip', models.CharField(choices=[('BONUS', 'Bonus'), ('ODBITAK', 'Odbitak')], max_length=10)),
                ('iznos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('opis', models.CharField(max_length=255)),
                ('evidencija', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonusi_odbitci', to='core.evidencijarada')),
            ],
            options={
                'verbose_name': 'Bonus / odbitak',
                'verbose_name_plural': 'Bonusi i odbitci',
            },
        ),
        migrations.CreateModel(
            name='Kategorija',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=100)),
                ('tip', models.CharField(choices=[('ARTIKL', 'Kategorija artikla'), ('TROSAK', 'Kategorija troška')], max_length=10)),
            ],
            options={
                'verbose_name': 'Kategorija',
                'verbose_name_plural': 'Kategorije',
                'ordering': ['naziv'],
                'unique_together': {('naziv', 'tip')},
            },
        ),
        migrations.CreateModel(
            name='Artikl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=150)),
                ('minimalna_razina', models.DecimalField(decimal_places=3, max_digits=10)),
                ('aktivan', models.BooleanField(default=True)),
                ('jedinica_mjere', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='artikli', to='core.jedinicamjere')),
                ('kategorija', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='artikli', to='core.kategorija')),
            ],
            options={
                'verbose_name': 'Artikl',
                'verbose_name_plural': 'Artikli',
                'ordering': ['naziv'],
            },
        ),
        migrations.CreateModel(
            name='ObracunPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('osnovna_placa', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ukupni_dodaci', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ukupni_odbitci', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('za_isplatu', models.DecimalField(decimal_places=2, max_digits=10)),
                ('datum_obracuna', models.DateTimeField(auto_now_add=True)),
                ('evidencija', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='obracun', to='core.evidencijarada')),
            ],
            options={
                'verbose_name': 'Obračun plaće',
                'verbose_name_plural': 'Obračuni plaća',
            },
        ),
        migrations.CreateModel(
            name='Racun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broj_racuna', models.CharField(max_length=100)),
                ('datum_racuna', models.DateField()),
                ('datum_dospijeca', models.DateField(blank=True, null=True)),
                ('ukupni_iznos', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('NEPLACENO', 'Neplaćeno'), ('PLACENO', 'Plaćeno')], default='NEPLACENO', max_length=20)),
                ('napomena', models.TextField(blank=True)),
                ('dobavljac', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='racuni', to='core.dobavljac')),
            ],
            options={
                'verbose_name': 'Račun',
                'verbose_name_plural': 'Računi',
                'ordering': ['-datum_racuna'],
            },
        ),
        migrations.CreateModel(
            name='StavkaRacuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kolicina', models.DecimalField(decimal_places=3, max_digits=10)),
                ('cijena_po_jedinici', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ukupno', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('artikl', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stavke_racuna', to='core.artikl')),
                ('racun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stavke', to='core.racun')),
            ],
            options={
                'verbose_name': 'Stavka računa',
                'verbose_name_plural': 'Stavke računa',
            },
        ),
        migrations.CreateModel(
            name='Trosak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=200)),
                ('iznos', models.DecimalField(decimal_places=2, max_digits=12)),
                ('datum', models.DateField()),
                ('opis', models.TextField(blank=True)),
                ('kategorija', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='troskovi', to='core.kategorija')),
            ],
            options={
                'verbose_name': 'Trošak',
                'verbose_name_plural': 'Troškovi',
                'ordering': ['-datum'],
            },
        ),
        migrations.CreateModel(
            name='Zaposlenik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=100)),
                ('prezime', models.CharField(max_length=100)),
                ('oib', models.CharField(max_length=11, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefon', models.CharField(blank=True, max_length=20)),
                ('datum_zaposlenja', models.DateField()),
                ('aktivan', models.BooleanField(default=True)),
                ('pozicija', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='zaposlenici', to='core.pozicija')),
            ],
            options={
                'verbose_name': 'Zaposlenik',
                'verbose_name_plural': 'Zaposlenici',
                'ordering': ['prezime', 'ime'],
            },
        ),
        migrations.CreateModel(
            name='Ugovor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip', models.CharField(choices=[('STUDENTSKI', 'Studentski ugovor'), ('STALNI', 'Stalni radni odnos')], max_length=20)),
                ('satnica', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('fiksna_placa', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('datum_pocetka', models.DateField()),
                ('datum_kraja', models.DateField(blank=True, null=True)),
                ('aktivan', models.BooleanField(default=True)),
                ('zaposlenik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ugovori', to='core.zaposlenik')),
            ],
            options={
                'verbose_name': 'Ugovor',
                'verbose_name_plural': 'Ugovori',
            },
        ),
        migrations.AddField(
            model_name='evidencijarada',
            name='zaposlenik',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencije', to='core.zaposlenik'),
        ),
        migrations.CreateModel(
            name='DnevnoStanje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField()),
                ('kolicina', models.DecimalField(decimal_places=3, max_digits=10)),
                ('potrosnja', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('artikl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dnevna_stanja', to='core.artikl')),
            ],
            options={
                'verbose_name': 'Dnevno stanje',
                'verbose_name_plural': 'Dnevna stanja',
                'ordering': ['-datum'],
                'unique_together': {('artikl', 'datum')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='evidencijarada',
            unique_together={('zaposlenik', 'mjesec', 'godina')},
        ),
    ]
