# Generated by Django 5.2.13 on 2026-06-28 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StavkaRacuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kolicina', models.DecimalField(decimal_places=3, max_digits=10)),
                ('cijena_po_jedinici', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ukupno', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('artikl', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stavke_racuna', to='core.artikl')),
                ('racun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stavke', to='core.racun')),
            ],
        ),
    ]
