# Generated by Django 5.2.13 on 2026-06-24 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ugovor',
            options={},
        ),
        migrations.RemoveField(
            model_name='ugovor',
            name='datum_kraja',
        ),
        migrations.RemoveField(
            model_name='ugovor',
            name='datum_pocetka',
        ),
    ]
