# Generated by Django 5.2.13 on 2026-06-28 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_stavkaracuna'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dnevnostanje',
            name='nabava',
        ),
    ]
