# Generated by Django 5.2.13 on 2026-06-24 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_ugovor_options_remove_ugovor_datum_kraja_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ugovor',
            options={'verbose_name': 'Ugovor', 'verbose_name_plural': 'Ugovori'},
        ),
        migrations.AddField(
            model_name='evidencijarada',
            name='fiksna_placa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='evidencijarada',
            name='satnica',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='evidencijarada',
            name='tip_ugovora',
            field=models.CharField(blank=True, choices=[('STUDENTSKI', 'Studentski ugovor'), ('STALNI', 'Stalni radni odnos')], max_length=20),
        ),
    ]
