# Generated by Django 5.2.13 on 2026-06-24 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_ugovor_options_evidencijarada_fiksna_placa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dnevnostanje',
            name='nabava',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
    ]
