# Generated by Django 5.2.13 on 2026-06-25 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_dnevnostanje_nabava'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ugovor',
            name='zaposlenik',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.zaposlenik'),
        ),
        migrations.DeleteModel(
            name='StavkaRacuna',
        ),
    ]
